### ISSUE TITLE
Inability to move content into bulma section

### ISSUE THREAD

**Issue by chriscarrel** [Purdue/bulma-blocks#1]
In firefox I am having issues moving standard blocks into bulma blocks.  I am able to create new blocks inside, just not move pre-existing ones into a new bulma section

**Comment by jyoung295** [comment]
I cannot reproduce this, I have no trouble moving blocks into bulma blocks. It can be sort of hard to tell now that they've removed all the outlines in the editor, so maybe in the future we should focus on trying to add back the outlines around blocks?
