### ISSUE TITLE
Ability to wrap default blocks in "section" class

### ISSUE THREAD

**Issue by chriscarrel** [Purdue/bulma-blocks#2]
When adding the Purdue WP theme content is not spaced correctly becuase the default Gutenberg blocks are not wrapped in "section" class and the spacing / display is off

**Comment by jyoung295** [comment]
We made the conscious decision not to add any layout classes wrapped around `the_content()` because then no full width content such as the site-hero would work. What do you suggest for the core blocks? Maybe if bulma-blocks isn't active then we wrap `the_content()` with a bulma section?
